import type { Metadata } from "next";
import {  Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Head from "next/head";

import { PrimeReactProvider } from "primereact/api";

const openSans = Open_Sans({
  variable: "--font-merriweather",
  weight: ["400", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Monirul Hassan",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className={`${openSans.className} bg-gray-100 dark:bg-slate-900`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <PrimeReactProvider>{children}</PrimeReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
